// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSD_vBKsPhbtknVL91FF1MWe0nrAOiwo4',
    appId: '1:926069728947:web:353d1891073fe40141b2c6',
    messagingSenderId: '926069728947',
    projectId: 'dalel-d9285',
    authDomain: 'dalel-d9285.firebaseapp.com',
    storageBucket: 'dalel-d9285.firebasestorage.app',
    measurementId: 'G-JQMXHSW3Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC401h8lBndARlotYTdbYgC1l4LzSEztzg',
    appId: '1:926069728947:android:e44c81e15fbff0a341b2c6',
    messagingSenderId: '926069728947',
    projectId: 'dalel-d9285',
    storageBucket: 'dalel-d9285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmE8KO81F82nmmeIVRo5CH0zng4DJ2io',
    appId: '1:926069728947:ios:3adc2df3fd72097a41b2c6',
    messagingSenderId: '926069728947',
    projectId: 'dalel-d9285',
    storageBucket: 'dalel-d9285.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQmE8KO81F82nmmeIVRo5CH0zng4DJ2io',
    appId: '1:926069728947:ios:3adc2df3fd72097a41b2c6',
    messagingSenderId: '926069728947',
    projectId: 'dalel-d9285',
    storageBucket: 'dalel-d9285.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSD_vBKsPhbtknVL91FF1MWe0nrAOiwo4',
    appId: '1:926069728947:web:73af9d55ee6a5b2041b2c6',
    messagingSenderId: '926069728947',
    projectId: 'dalel-d9285',
    authDomain: 'dalel-d9285.firebaseapp.com',
    storageBucket: 'dalel-d9285.firebasestorage.app',
    measurementId: 'G-0WXDXX3VR6',
  );
}
